# Generated by Django 2.2.4 on 2020-12-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0002_auto_20201224_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='iconLink',
        ),
    ]
