# Generated by Django 2.2.4 on 2020-12-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0003_remove_category_iconlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='iconLink',
            field=models.TextField(default=''),
        ),
    ]
