# Generated by Django 2.2.4 on 2020-12-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_auto_20201224_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checked_out',
        ),
    ]
